// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import ClientProviders from "@/providers/client-providers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const langCookie = cookieStore.get("lang")?.value as "en" | "ro" | undefined;
  const lang = langCookie ?? "en";

  return (
    <html lang={lang} suppressHydrationWarning>
      <body>
        <ClientProviders initialLang={lang}>{children}</ClientProviders>
      </body>
    </html>
  );
}
