/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 abstract_rainbow_translucent_pendant.glb -T 
Files: abstract_rainbow_translucent_pendant.glb [1.9MB] > D:\Projects\Personal\GitHub\nextjs_portfolio\public\3d-scenes\abstract_rainbow_translucent_pendant-transformed.glb [77.52KB] (96%)
Author: riach (https://sketchfab.com/riach)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-rainbow-translucent-pendant-fd730e2886e748a0bd645d05fd96040d
Title: Abstract Rainbow Translucent Pendant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/abstract_rainbow_translucent_pendant-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Hedra001_Material_#0_0'].geometry} material={materials.Material_0} position={[-0.016, 0, 0.088]} rotation={[-Math.PI / 2, 0, 0]} scale={0.016} />
    </group>
  )
}

useGLTF.preload('/abstract_rainbow_translucent_pendant-transformed.glb')
